### ISSUE TITLE
QuestionController

### ISSUE THREAD

**Issue by TommyCpp** [TeamYouthChina/backend#110]

**Comment by jonathan12zhang** [comment]
- [ ] Answer DTO
- [ ] Question DTO
- [ ] Question Controller

**Comment by jonathan12zhang** [comment]
In the API you given, the question has a post method with an invite variable. However, in both the question domain and dto, there is no integer variable called invite and no get or set method with invite. We also confused about what does this invite variable means.

**Comment by jonathan12zhang** [comment]
Question request more information from front end such as List<Integer> labels, Integer rele_type, Integer rele_id.
