### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by TommyCpp** [TeamYouthChina/backend#68]

**Comment by hmgswqh** [comment]
DTO缺少职位申请表DTO，职位收藏DTO，公司收藏DTO

**Comment by ctijia** [comment]
AnswerController 前端Answer部分，添加answer时传参少问题id(ques_id)和楼层数(level)，添加comment参数不明

**Comment by JINHAOHU** [comment]
Answer 的 get 里面 content 没有内容

**Comment by TommyCpp** [comment]
- [ ] Resume

- [ ] Personal Info - skill

**Comment by IrvingZhao2018** [comment]
- [ ] location API
