### ISSUE TITLE
location service

### ISSUE THREAD

**Issue by JINHAOHU** [TeamYouthChina/backend#84]
重点在合并google和高德的api

**Comment by IrvingZhao2018** [comment]
- [ ] Location to USA & China

**Comment by TommyCpp** [comment]
API 国家代码查询
没有参数，返回国家代码CHN 国名中国

API 中国省市查询
输入 六位数字字符串
输出 列表 六位数字字符串 地理位置字符串

**Comment by IrvingZhao2018** [comment]
Location: Get Children(subLocation)
